#!/usr/bin/env bash

check_rs=0
check_ts=0

declare -a extra_flags=("" "--cached")

for flag in ${extra_flags[@]}; do
    git diff --name-only $flag | grep '.rs$' > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        check_rs=1
    fi

    git diff --name-only $flag | grep -E '.ts$|.json$|.yml$' > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        check_ts=1
    fi
done

if (( $check_rs != 0 )); then
    cargo make check-rs-format
    ret=$?
    if [ $? -ne 0 ]; then
       return $ret
    fi
fi

if (( $check_ts != 0 )); then
    cargo make check-ts-format
    ret=$?
    if [ $? -ne 0 ]; then
       return $ret
    fi
fi

exit 0
