#!/usr/bin/env bash

set -e                          # grep failure does not trigger exit.

debug=0                         # Set to 1 to enable debugging, 0 to disable.

function check_rs() {
    if (( debug == 0 )); then
        cargo make check-rs-format
    else
        echo "check_rs ran"
    fi
}

function check_ts() {
    if (( debug == 0 )); then
        cargo make check-ts-format
    else
        echo "check_ts ran"
    fi
}

git status --untracked-files=no --short | grep -E '.rs$' > /dev/null 2>&1 && check_rs
git status --untracked-files=no --short | grep -E '.ts$|.json$|.yml$' > /dev/null 2>&1 && check_ts

exit 0
