pull_request_rules:
  - name: merge on CI success and 2 approvals
    conditions:
      - "status-success=ci/circleci: build"
      - "#approved-reviews-by>=2"
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head!~=^release/.*
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: merge
      delete_head_branch:
  - name: merge green dependabot PRs
    conditions:
      - "status-success=ci/circleci: debug-build-test"
      - "author:dependabot-preview[bot]"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: merge
      delete_head_branch:
