pull_request_rules:
  - name: comment on broken dependabot PRs, asking for help
    conditions:
      - "author=dependabot-preview[bot]"
      - "status-failure=build (ubuntu-latest)"
    actions:
      comment:
        message: "The build on this dependency update is broken and needs attention."
      request_reviews:
        teams:
          - "@comit-network/rust-devs"
  - name: instruct bors to merge dependabot PRs with passing tests
    conditions:
      - "author=dependabot-preview[bot]"
      - "status-success=static_analysis"
      - "status-success=build (ubuntu-latest)"
      - "status-success=e2e_test (ubuntu-latest)"
      - "status-success=license/cla"
      - label!=no-mergify
    actions:
      comment:
        message: "bors r+"
  - name: instruct bors to merge PRs with passing tests and 2 approvals
    conditions:
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "status-success=static_analysis"
      - "status-success=build (ubuntu-latest)"
      - "status-success=e2e_test (ubuntu-latest)"
      - "status-success=license/cla"
      - -conflict
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
      - head~=^(?!release.*).*$
    actions:
      delete_head_branch:
  - name: nag if changelog is not updated
    conditions:
      - "author!=dependabot-preview[bot]"
      - "files!=CHANGELOG.md"
      - review-requested!=''
    actions:
      comment:
        message: "Are you sure the changelog does not need updating?"
